### ISSUE TITLE
Memrise Cards [Lt], space bar button

### ISSUE THREAD

**Issue by Gardengul** [Eltaurus-Lt/Anki-Card-Templates#15]
Anki 24.06.2 (33a92379)  (ao) 
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1 
Platform: Windows-10-10.0.19045

When you turn on the addon Memrise Cards [Lt], the space bar does not work during the review.

**Comment by Eltaurus-Lt** [comment]
What would be the expected behaviour for the space bar in this case?

**Comment by Gardengul** [comment]
![image](https://github.com/Eltaurus-Lt/Anki-Card-Templates/assets/95347489/afcc893c-83c0-4b4d-b3c1-1390f6ccb582)

The space bar button shows the answer and if the answer is already shown, responds to the card as good.

**Comment by Eltaurus-Lt** [comment]
If you want the spacebar to act like the Enter key you can substitute the following expression on the front of a card
```
ev.key === 'Enter'
```
with this:
```
(ev.key === 'Enter' || ev.key === ' ')
```
I won't make this change in the general template, as I have a different use for a space button for the future versions in mind, and it is not a behaviour people would expect from a Memrise template anyway.

**Comment by Gardengul** [comment]
I meant that the space bar does not work with all note types, not just with Memrise (Long) Preset [...] v3.32

**Comment by Eltaurus-Lt** [comment]
Thats right. But any shortcut used by Anki itself becomes inaccessible from card scripts. So there are basically only two ways around it:
1. Return the shortcuts back to Anki by commenting out the first line:
   ```
   from . import Clear_Shortcuts
   ```
   in `__init__.py` file in the add-on folder. (this will also disable autorating scripts on the memrise cards)
2. Keep the add-on as is, and add the JS processing Enter and Space keys to all the Note Types that require it.

**Comment by Gardengul** [comment]
I thought it was a bug. But if this is not the case, then everything is fine.

**Comment by Eltaurus-Lt** [comment]
> It would be good to access disabling/enabling this feature via config.

You can remove any of the keys reserved by the Add-on for the template from the config in the current version of the Add-on to revert the key back to its default Anki behavior.

**Comment by Eltaurus-Lt** [comment]
Full instructions for modifying any template in the release notes post:
https://forums.ankiweb.net/t/memrise-card-template-support-thread/34233/156?u=eltaurus

**Comment by Eltaurus-Lt** [comment]
> I meant that the space bar does not work with all note types, not just with Memrise (Long) Preset [...] v3.32

Now spacebar and other shortcuts are altered only when reviewing any of the template's cards. All other note types are not affected and no config adjustments are needed.
