### ISSUE TITLE
Disable typing?

### ISSUE THREAD

**Issue by whereistimbo** [Eltaurus-Lt/Anki-Card-Templates#16]
How can I disable typing and just use multiple choice?

**Comment by Eltaurus-Lt** [comment]
From the main menu go to `Tools` -> `Manage Note Types` -> select the template you are using and press `Cards`.
At the top you'll see the dropdown menu with the card types included in the template. You can delete the ones you don't need by pressing `Options` -> `Remove Card Type` to the left of it.

**Comment by whereistimbo** [comment]
Thank you!
