### ISSUE TITLE
Multiple choice not showing up; need to support images in multiple choices.

### ISSUE THREAD

**Issue by whereistimbo** [Eltaurus-Lt/Anki-Card-Templates#18]
For comparison:
In Anki Card Templates:
<img width="662" alt="Screen Shot 2024-07-06 at 23 16 43" src="https://github.com/Eltaurus-Lt/Anki-Card-Templates/assets/47355692/eaab4847-bfdd-4de5-a34c-03cc2e431a8b">

In Memrise Community Course:
<img width="814" alt="Screen Shot 2024-07-06 at 23 21 36" src="https://github.com/Eltaurus-Lt/Anki-Card-Templates/assets/47355692/84f72357-d5c8-40cb-a9b5-06d05447bc79">

Debug info:
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-11.7.10-x86_64-i386-64bit

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Memrise Cards Lt ['884199977', 2024-04-11T13:48, 'None', '']

===IDs of active AnkiWeb add-ons===
884199977

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by whereistimbo** [comment]
Course link: https://community-courses.memrise.com/community/course/1087087/hebrew-alef-bet-print/
My downloaded course: 
[hebrew-alef-bet-print by Mazzorano [1087087].zip](https://github.com/user-attachments/files/16116741/hebrew-alef-bet-print.by.Mazzorano.1087087.zip)

**Comment by Eltaurus-Lt** [comment]
As mentioned in [the release notes](https://forums.ankiweb.net/t/memrise-card-template-support-thread/34233/54?u=eltaurus):
[quote="Eltaurus, post:54, topic:34233"]
Images in the multiple-choice fields will not work in the current version.
[/quote]

The update for that is being prepared, and already works on most of the systems. You can try it out (at your own risk) from this branch: https://github.com/Eltaurus-Lt/Anki-Card-Templates/tree/31e8b199c2bb83539c0cea567ad7df5a086b839d

**Comment by whereistimbo** [comment]
I'm so sorry for my foolishness, thanks for the heads up, should I keep this issue open?

**Comment by Eltaurus-Lt** [comment]
It's alright. If you leave the thread I'll link it to the respective fixes later. This way you should be notified when they get merged into the main branch (and the issue will be closed automatically).

**Comment by Eltaurus-Lt** [comment]
@whereistimbo if you don't mind me asking, did you use some extension to enable a dark theme on the Memrise site?

**Comment by whereistimbo** [comment]
> @whereistimbo if you don't mind me asking, did you use some extension to enable a dark theme on the Memrise site?

No, I'm using built-in feature of Microsoft Edge on macOS Big Sur to enable dark mode (behind feature flags).

**Comment by Eltaurus-Lt** [comment]
The images in multiple-choice questions are fully supported in the updated version (v4.2).

Moreover, the template has dedicated dark themes now:
![image](https://github.com/user-attachments/assets/64da7167-7bb2-42fb-ad61-3cc424eae471)

You can also make your letter images appear without background (the white rectangles) and change color depending on light/dark theme by adding a small piece of code to the "⚙️ USER STYLES ⚙️" section (you'll find it at the very bottom of the Styling tab when editing the new template):
```
img {
 mix-blend-mode: multiply;
}

body:is(.nightMode, .night_mode) img {
 filter: invert();
 mix-blend-mode: screen;
}
```
