### ISSUE TITLE
Not working on iPadOS

### ISSUE THREAD

**Issue by cor-bee** [Eltaurus-Lt/Anki-Card-Templates#21]
It seems that despite everything renders right on iPad, some crucial options like multiple choice buttons and auto-checking "Good" doesn't work.

I'll look into that later and try to figure out how to fix that.

**Comment by Eltaurus-Lt** [comment]
iOS is not supported in the current version of the template. 
It is planned to be added in the next one.

**Comment by Eltaurus-Lt** [comment]
> auto-checking "Good"

this, as well as automatically flipping to the backside after pressing a multiple-choice button or typing the full answer with "Hint", can't be implemented, [unless Anki on phones gets a public API for these actions](https://forums.ankiweb.net/t/trigger-show-answer-fliptoback-in-javascript/36643/4?u=eltaurus)
