### ISSUE TITLE
Can you display a tag or attribute on the card?

### ISSUE THREAD

**Issue by stuckinthe** [Eltaurus-Lt/Anki-Card-Templates#5]
Is there a way to display a tag or attribute on the card. For example, my Memrise deck had noun, adjective etc. How can I display these tags since they vary. They move over from the import as a category or whatever I want to set it to.

**Comment by stuckinthe** [comment]
It is on the card as Extra but it doesn't show up.

**Comment by Eltaurus-Lt** [comment]
The ‘Extra` field should be visible on the back of the card. You want to move it to the front, is that what the question is about?

**Comment by stuckinthe** [comment]
I have mine setup to type in the correct answer so there really isn't a back card. I ended up putting the extra tag below the definition tag and it displays.
